//URLs API
export const DEVELOP_URL = 'http://localhost:51828/api';

// Products
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CHANGE_FILTER_CATEGORY = 'CHANGE_FILTER_CATEGORY';

// Product Specifications
export const FETCH_PRODUCT_SPECIFICATIONS = 'FETCH_PRODUCT_SPECIFICATIONS';

// Categories
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CHANGE_FILTER_CATEGORY_CREATE_PRODUCT = 'CHANGE_FILTER_CATEGORY_CREATE_PRODUCT';

// Specifications
export const FETCH_SPECIFICATIONS = 'FETCH_SPECIFICATIONS';

// DetailSpecifications
export const FETCH_DETAIL_SPECIFICATIONS = 'FETCH_DETAIL_SPECIFICATIONS';
export const CHANGE_FILTER_DETAIL_SPECIFICATION = 'CHANGE_FILTER_DETAIL_SPECIFICATION';


// User
export const CURRENT_USER = 'sample';

// Shooping Carts 
export const FETCH_SHOOPING_CARTS_BY_USERNAME = 'FETCH_SHOOPING_CARTS_BY_USERNAME';
